services:
    
  greenhouse:
    image: nginx
    container_name: greenhouse
    restart: unless-stopped
    networks:
      - npm_network
    volumes:
      - ./greenhouse:/usr/share/nginx/html:ro

networks:
    
  npm_network:
    name: npm_network
    external: true
