services:

  npm:
    image: jc21/nginx-proxy-manager
    container_name: npm
    restart: unless-stopped
    volumes:
      - npm-data:/data
      - npm-letsencrypt:/etc/letsencrypt
    networks:
      - npm_network
    ports:
      - 80:80
      - 81:81
      - 443:443

volumes:

  npm-data:
  npm-letsencrypt:

networks:
    
  npm_network:
    name: npm_network
