services:

  npm:
    image: jc21/nginx-proxy-manager:latest
    container_name: npm
    restart: unless-stopped
    volumes:
      - npm-data:/data
      - npm-letsencrypt:/etc/letsencrypt
    networks:
      - banter-network
    ports:
      - 80:80
      - 81:81
      - 443:443

  hub:
    image: arteeh/banter-hub
    container_name: hub
    restart: unless-stopped
    networks:
      - banter-network
    build:
      context: ./hub

  # hub:
  #   image: arteeh/banter-hub
  #   container_name: banter
  #   restart: unless-stopped
  #   networks:
  #     - banter-network
  #   build:
  #     context: ./banter

volumes:

  npm-data:
  npm-letsencrypt:

networks:

  banter-network:
