services:
    
  hub:
    image: arteeh/hub
    container_name: hub
    restart: unless-stopped
    networks:
      - network
    ports:
      - 7770:80
    build:
      context: .
      dockerfile: ./Hub/Dockerfile

  greenhouse:
    image: arteeh/greenhouse
    container_name: greenhouse
    restart: unless-stopped
    networks:
      - network
    ports:
      - 7771:80
    build:
      context: .
      dockerfile: ./Greenhouse/Dockerfile
    
  greenhousejs:
    image: nginx
    container_name: greenhousejs
    restart: unless-stopped
    networks:
      - network
    ports:
      - 7772:80
    volumes:
      - ./GreenhouseJS:/usr/share/nginx/html:ro
    
  npm:
    image: jc21/nginx-proxy-manager
    container_name: npm
    restart: unless-stopped
    volumes:
      - npm-data:/data
      - npm-letsencrypt:/etc/letsencrypt
    networks:
      - network
    ports:
      - 80:80
      - 81:81
      - 443:443

volumes:
    
  npm-data:
  npm-letsencrypt:

networks:
    
  network:
