services:

  npm:
    image: jc21/nginx-proxy-manager
    container_name: npm
    restart: unless-stopped
    volumes:
      - data:/data
      - letsencrypt:/etc/letsencrypt
    networks:
      - network
    ports:
      - 80:80
      - 81:81
      - 443:443

volumes:

  data:
  letsencrypt:

networks:
    
  network:
